# Generated by Django 4.1 on 2024-03-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uyeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eposta', models.EmailField(max_length=100, verbose_name='E-Posta Adresi')),
                ('parola', models.CharField(max_length=50, verbose_name='Parola')),
                ('adi', models.CharField(max_length=50, verbose_name='Adi')),
                ('soyadi', models.CharField(max_length=50, verbose_name='Soyadi')),
                ('kullaniciFoto', models.ImageField(upload_to='', verbose_name='Kullanıcı Fotoğrafı')),
            ],
            options={
                'verbose_name': 'Üye',
                'verbose_name_plural': 'Üyeler',
            },
        ),
    ]
