# Generated by Django 5.0.2 on 2024-02-22 16:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DuyuruBaslik', models.CharField(max_length=100, verbose_name='Duyuru Baslik')),
                ('DuyuruIcerik', tinymce.models.HTMLField(max_length=200, verbose_name='Icerigi: ')),
            ],
        ),
    ]
