# Generated by Django 5.0.2 on 2024-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorselBaslik', models.CharField(max_length=100, verbose_name='Gorsel Basligi: ')),
                ('image', models.ImageField(upload_to='', verbose_name='Galeri Gorseli: ')),
            ],
            options={
                'verbose_name': 'gorsel',
                'verbose_name_plural': 'gorseller',
            },
        ),
        migrations.AlterModelOptions(
            name='duyurular',
            options={'verbose_name': 'Duyurular', 'verbose_name_plural': 'Duyurular'},
        ),
    ]
