# Generated by Django 5.0.2 on 2024-02-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browny_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazar',
            options={'verbose_name': 'yazar', 'verbose_name_plural': 'yazarlar'},
        ),
        migrations.AlterField(
            model_name='haberler',
            name='yazar',
            field=models.ForeignKey(blank=True, help_text='seçiniz: ', null=True, on_delete=django.db.models.deletion.CASCADE, to='browny_app.yazar', verbose_name='Yazar seçiniz'),
        ),
    ]
