# Generated by Django 4.1 on 2023-03-14 17:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yonetmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adiSoyadi', models.CharField(max_length=50, verbose_name='Yönetmen Ad Soyad')),
                ('eposta', models.CharField(max_length=50, verbose_name='Eposta Adresi')),
            ],
        ),
        migrations.CreateModel(
            name='Filmler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Film Başlığı')),
                ('turu', models.CharField(max_length=50, verbose_name='Film Türü')),
                ('konu', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Film Konusu')),
                ('gosterimdeMi', models.BooleanField(default=True, verbose_name='Gösterimde Mi:')),
                ('gosterimTarihi', models.DateTimeField(verbose_name='Gösterim Tarihi')),
                ('oyuncu', models.CharField(choices=[('1', 'Haluk Bilginer'), ('2', 'Kemal Sunal'), ('3', 'Halit Akçatepe'), ('4', 'Güneş Emir')], max_length=50, verbose_name='Oyuncu Seç')),
                ('filmAfis', models.CharField(max_length=100, verbose_name='Film Başlığı')),
                ('biletFiyat', models.FloatField(blank=True, null=True, verbose_name='Bilet Fiyat')),
                ('director', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmler.yonetmen', verbose_name='Yonetmen Bilgisi')),
            ],
        ),
    ]
