# Generated by Django 4.1 on 2023-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Görsel Başlık')),
                ('image', models.ImageField(upload_to='', verbose_name='Fotoğraf Seçin')),
            ],
        ),
    ]
