# Generated by Django 4.1 on 2023-03-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0002_galeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmler',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Film Afişi'),
            preserve_default=False,
        ),
    ]
