# Generated by Django 4.1 on 2024-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0003_filmler_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oyuncular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(max_length=64, verbose_name='Ad Soyad')),
            ],
        ),
        migrations.AlterModelOptions(
            name='filmler',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmler'},
        ),
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name': 'Galeri', 'verbose_name_plural': 'Galeriler'},
        ),
        migrations.AlterModelOptions(
            name='yonetmen',
            options={'verbose_name': 'Yönetmen', 'verbose_name_plural': 'Yönetmenler'},
        ),
        migrations.RemoveField(
            model_name='filmler',
            name='oyuncu',
        ),
        migrations.AddField(
            model_name='filmler',
            name='oyuncu',
            field=models.ManyToManyField(blank=True, to='filmler.oyuncular', verbose_name='Oyuncu Seçin:  '),
        ),
    ]
