# Generated by Django 4.1 on 2024-03-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0004_oyuncular_alter_filmler_options_alter_galeri_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oyuncular',
            options={'verbose_name': 'Oyuncu', 'verbose_name_plural': 'Oyuncular'},
        ),
        migrations.AlterField(
            model_name='filmler',
            name='oyuncu',
            field=models.ManyToManyField(to='filmler.oyuncular', verbose_name='Oyuncu Seçin'),
        ),
    ]
