# Generated by Django 4.2.10 on 2024-02-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adiSoyadi', models.CharField(max_length=50, verbose_name='Yazar Adı:')),
                ('eposta', models.EmailField(max_length=254, verbose_name='E-Posta Adresi:')),
            ],
        ),
        migrations.CreateModel(
            name='Haberler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50, verbose_name='Haber Başlığı:')),
                ('icerik', models.CharField(max_length=50, verbose_name='İçerik:')),
                ('tarih', models.DateField(verbose_name='Yayın Tarihi:')),
                ('gorsel', models.ImageField(upload_to='', verbose_name='Görsel Seçiniz:')),
                ('yazar', models.OneToOneField(blank=True, help_text='Seçiniz.', null=True, on_delete=django.db.models.deletion.CASCADE, to='browny_app.yazar', verbose_name='Yazar Seçiniz')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
            },
        ),
    ]
