# Generated by Django 4.2.10 on 2024-02-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browny_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazar',
            options={'verbose_name': 'Yazar', 'verbose_name_plural': 'Yazarlar'},
        ),
    ]
