# Generated by Django 4.2.10 on 2024-02-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browny_app', '0002_alter_yazar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haberler',
            name='yazar',
            field=models.ForeignKey(blank=True, help_text='Seçiniz.', null=True, on_delete=django.db.models.deletion.CASCADE, to='browny_app.yazar', verbose_name='Yazar Seçiniz'),
        ),
    ]
